/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pikabobalex (https://sketchfab.com/pikabobalex)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/phonograph-v2-746b3e65cc5b494b97aee6088eccc7a5
title: Phonograph-v2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/phonograph.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.2, -0.3]} rotation={[-Math.PI / 2.2, 0, 1]} scale={0.08}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['phonograph_phonograph-mat_0'].geometry} material={materials['phonograph-mat']} />
          </group>
          {/* <group position={[0, -0.17, -0.3]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.table_table_mat_0.geometry} material={materials.table_mat} />
          </group> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/phonograph.gltf')
